app/publication/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField, SelectField, IntegerField, DecimalField
from wtforms.validators import DataRequired, Length,Email, EqualTo, ValidationError
from wtforms.ext.sqlalchemy.fields import QuerySelectField

from ..models import Categorie


def rech_categorie():
    return Categorie.query.filter_by(statut=True).all()


class AjoutPubForm(FlaskForm):
    titre= StringField('Titre', validators=[DataRequired("Completer le titre"),  Length(min=2, max=255, message="Veuillez respecté les caractères")])
    resume= TextAreaField('Resume', validators=[DataRequired("Completer le resumé")])
    categorie= QuerySelectField(query_factory=rech_categorie, get_label='nom', allow_blank=False)
    image_article = FileField('Image', validators=[FileAllowed(['jpg','png'],'Seul jpg et png sont autorisé')])
    pdf_document = FileField('Image', validators=[FileAllowed(['pdf'],'Seul pdf est autorisé')])
    url = StringField('url')
    submit = SubmitField('Ajouter publication')


class EditPubForm(FlaskForm):
    titre= StringField('Titre', validators=[DataRequired("Completer le titre"),  Length(min=2, max=255, message="Veuillez respecté les caractères")])
    resume= TextAreaField('Resume', validators=[DataRequired("Completer le resumé")])
    url = StringField('url')
    categorie= QuerySelectField(query_factory=rech_categorie, get_label='nom', allow_blank=False)
    submit = SubmitField('Ajouter publication')


class AjMediaForm(FlaskForm):
    image_article = FileField('Image', validators=[FileAllowed(['jpg','png'],'Seul jpg est autorisé')])
    submit = SubmitField('Publier')

class AjPDFForm(FlaskForm):
    image_article = FileField('Image', validators=[FileAllowed(['pdf'],'Seul pdf est autorisé')])
    submit = SubmitField('Publier')

app/publication/__init__.py
from flask import Blueprint

publication = Blueprint('publication', __name__, url_prefix='/publication')
# never forget 
from . import routes

app/publication/routes.py
import os
from flask import render_template, flash, url_for, redirect, request, session
from .. import db, bcrypt
from ..models import Categorie, Publication, Historique, Fichier
from app.publication.forms import AjoutPubForm, EditPubForm, AjMediaForm, AjPDFForm
from flask_login import login_user, current_user, logout_user, login_required
from ..utilites.utility import find_url, title_page, slug_publication, message_historique, date_modification
from slugify import slugify
from . import publication
from .upload import publication_doc, save_image_mod
import timeago
from datetime import datetime



''' Ajouter une publication '''
@publication.route('/ajouter', methods=['GET','POST'])
@login_required
def ajouter():
   title=title_page('Publication')
   #formulaire
   form=AjoutPubForm()
   #Vérfication des catégories existant
   ver_categorie=Categorie.query.filter_by(statut=True).first()
   if ver_categorie is None:
      return redirect(url_for('categorie.ajoutcate'))
   
   

   if form.validate_on_submit():
      ver_video=form.url.data   
      url_youtube=None
      if ver_video !='' or  find_url(form.url.data)==1 :
         if ver_video !='':
            if find_url(form.url.data)==1:
               #Vérification de chaine de caractère
               if "watch?v=" in str(form.url.data):
                  url_video =str(form.url.data)
                  url_video = url_video.replace("watch?v=", "embed/")
                  url_youtube=url_video
               else:
                  url_youtube=form.url.data  
            else:
               flash("Le lien de la vidéo",'danger')
               return redirect(url_for('media.ajouter'))

      #Titre de l'article
      titre_slug=slug_publication(form.titre.data)
      document_pub=publication_doc(form.pdf_document.data)
      image_pub=publication_doc(form.image_article.data)
      #Enregistrement de la publication
      pub=Publication(titre=form.titre.data, resume=form.resume.data, slug=titre_slug, url_img=image_pub,
                        categorie_id=form.categorie.data.id, user_pub=current_user, url_youtube=url_youtube)
      db.session.add(pub)
      db.session.commit()
      #Enregistrement du fichier
      if document_pub is not None:
         fichier_pdf=Fichier(url_pdf=document_pub, pub_fic=pub)
         db.session.add(fichier_pdf)
         db.session.commit()
      message=f"Ajout de la publication de:{form.titre.data}"
      message_historique(message=message, user_ide=current_user.id)
      flash("Publication ajoutée",'success')
      return redirect(url_for('publication.index')) 

   return render_template('publication/ajouter.html',  title=title, form=form)

""" Liste des publications """
@publication.route('/', methods=['GET', 'POST'])
def index():
   #Titre
   title=title_page('Publication')
   #Requête d'affichage des categoriesÒ
   listes=Publication.query.order_by(Publication.id.desc()).all()
   #Taille de publication   
   taille=len(listes)

   return render_template('publication/index.html',title=title, liste=listes, taille=taille)

""" Modification de la publication """
@publication.route('/edit_<int:pub_id>_pub', methods=['GET', 'POST'])
def edit(pub_id):

   form=EditPubForm()
   #Titre
   title=title_page('Publication')
   #Requête de vérification du type
   pub_c=Publication.query.filter_by(id=pub_id).first()
   #Titre de la publication
   pub_titre=pub_c.titre

   if pub_titre is None:
      return redirect(url_for('publication.index'))
   
   if form.validate_on_submit():
      ver_video=form.url.data   
      url_youtube=None

      
      if ver_video !='' or  find_url(form.url.data)==1 :
         if ver_video !='':
            if find_url(form.url.data)==1:
               #Vérification de chaine de caractère
               if "watch?v=" in str(form.url.data):
                  url_video =str(form.url.data)
                  url_video = url_video.replace("watch?v=", "embed/")
                  url_youtube=url_video
               else:
                  url_youtube=form.url.data  
            else:
               flash("Le lien de la vidéo",'danger')
               return redirect(url_for('media.ajouter'))
            
      titre_slug=slug_publication(form.titre.data) 
      pub_c.titre=form.titre.data
      pub_c.slug=titre_slug
      pub_c.resume=form.resume.data
      pub_c.date_mod=date_modification()
      pub_c.categorie_id=form.categorie.data.id
      pub_c.url_youtube=url_youtube
      db.session.commit()
      #Enregistrement
      message=f"Modification de la publication de:{form.titre.data}"
      publication_de=f"{current_user.prenom} {current_user.post_nom}"
      message_historique(message=message, user_ide=current_user.id)

      flash("Modification réussie",'primary')
      return redirect(url_for('publication.index'))
      
   if request.method=='GET':
      form.titre.data=pub_c.titre
      form.resume.data=pub_c.resume
      form.categorie.data=pub_c.cat_pub
      form.url.data=pub_c.url_youtube

   return render_template('publication/edit.html', form=form, title=title)


""" Modification de l'image de la publication """
@publication.route('/edit_<int:pub_id>_image', methods=['GET', 'POST'])
def edit_image(pub_id):

   form=AjMediaForm()
   #Titre
   title=title_page('Publication')
   #Requête de vérification du type
   pub_c=Publication.query.filter_by(id=pub_id).first()
   #Titre de la publication
   pub_titre=pub_c.titre

   if pub_c is None:
      return redirect(url_for('publication.index'))
   #Modification de l'image
   if form.validate_on_submit():
      image_pub=save_image_mod(form.image_article.data, pub_c.url_img)
      if image_pub is None:
         return redirect(url_for('publication.edit_image',pub_id=pub_id))
      pub_c.url_img=image_pub
      pub_c.date_mod=date_modification()
      db.session.commit()
      #Enregistrement
      message=f"Modification de l'image de la publication de:{pub_titre}"
      publication_de=f"{current_user.prenom} {current_user.post_nom}"
      message_historique(message=message, user_ide=current_user.id)

      flash("Modification réussie",'primary')
      return redirect(url_for('publication.index'))


   return render_template('publication/editim.html', form=form, title=title, titre=pub_titre)


""" Modification du PDF de la publication """
@publication.route('/edit_<int:pub_id>_pdf', methods=['GET', 'POST'])
def edit_pdf(pub_id):
   #Formulaire
   form=AjPDFForm()
   #Titre
   title=title_page('Publication')
   #Requête de vérification du type
   pub_c=Publication.query.filter_by(id=pub_id).first()
   #Titre de la publication
   pub_titre=pub_c.titre
   #Vérifcation des fichiers
   fic_publier=Fichier.query.filter_by(publication_id=pub_id).first()
   #Ancien fichier
   fichier_ancien=None
   if fic_publier is not None:
      fichier_ancien=fic_publier.url_pdf

   if pub_c is None:
      return redirect(url_for('publication.index'))
   #Modification de l'image
   if form.validate_on_submit():

      image_pub=save_image_mod(form.image_article.data, fichier_ancien)
      if image_pub is None:
            return redirect(url_for('publication.edit_pdf',pub_id=pub_id))

      if fic_publier is not None:
         fic_publier.url_pdf=image_pub
         pub_c.date_mod=date_modification()
      else:
         image_en=Fichier(url_pdf=image_pub, publication_id=pub_id)
         db.session.add(image_en)
      
      message=f"Modification du PDF de la publication de:{pub_titre}"
      publication_de=f"{current_user.prenom} {current_user.post_nom}"
      message_historique(message=message, user_ide=current_user.id)

      db.session.commit()
      flash("Modification réussie",'primary')
      return redirect(url_for('publication.index'))
   return render_template('publication/editpdf.html', form=form, title=title, titre=pub_titre)


""" Modifier statut de l'Utilisateur """
@publication.route('/statut/<int:pub_id>', methods=['GET', 'POST'])
def statut(pub_id):
   #Titre
   title=title_page('Publication')
   #Requête de vérification du type
   pub_c=Publication.query.filter_by(id=pub_id).first()

   if pub_c is None:
      return redirect(url_for('publication.index'))

   if pub_c.statut == True:
      pub_c.statut=False
      db.session.commit()
      flash("La publication est désactivée sur la plateforme",'primary')
      return redirect(url_for('publication.index'))
   else:
      pub_c.statut=True
      db.session.commit()
      flash("La publication est activée sur la plateforme",'primary')
      return redirect(url_for('publication.index'))
   
   return render_template('user/index.html',title=title)


""" Modifier à la une """
@publication.route('/alaune/<int:pub_id>', methods=['GET', 'POST'])
def alune(pub_id):
   #Titre
   title=title_page('Publication')
   #Requête de vérification du type
   pub_c=Publication.query.filter_by(id=pub_id).first_or_404()
   
   #Vérification
   pub_all=Publication.query.filter_by(pred_jour=True).first()
   if pub_all is not None:
      pub_all.pred_jour=False
      db.session.commit()
   
   #L'article ne pas 
   if pub_c is None:
      return redirect(url_for('publication.index'))

   #Mise à jour de la predication à la une
   if pub_c.pred_jour == True:
      pub_c.pred_jour=False
      db.session.commit()
      flash("La publication n'est plus à la une",'success')
      return redirect(url_for('publication.index'))
   else:
      pub_c.pred_jour=True
      db.session.commit()
      flash("La publication est à la une",'success')
      return redirect(url_for('publication.index'))
   
   return render_template('user/index.html',title=title)

app/templates/publication/ajouter.html
{% extends "layout/admini.html" %}
{% block css %}
<link rel="stylesheet" href="{{url_for('static', filename='nv_admin/vendors/choices.js/choices.min.css')}}" />
<link rel="stylesheet" href="{{url_for('static', filename='nv_admin/vendors/summernote/summernote-lite.min.css')}}" >
{%endblock%}




{% block body %}
  <div class="row">
      <div class="col-12 col-md-6 order-md-1 order-last">
          <h3>Publications</h3>
      </div>
      <div class="col-12 col-md-6 order-md-2 order-first">
          <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{url_for('main.dashboard')}}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{url_for('publication.index')}}">Les publications</a></li>
                <li class="breadcrumb-item active" aria-current="page">Ajouter publication</li>
              </ol>
          </nav>
      </div>
  </div>

  <div class="row">
          <div class="col-md-12"> 
            <div class="row">
              <div class="col-md-10">
                <div class="card card-outline-secondary box-shadow--3dp">
                  <div class="card-body">
                    <h3><b>Ajouter une publication</b></h3> <br>
                    {% with messages= get_flashed_messages(with_categories=true) %}
                    {% if messages  %}
                        {% for category, message in messages %}
                            <div class="alert text-center alert-{{ category }}">
                                <b>{{ message }}</b>
                            </div>
                        {% endfor %}
                    {% endif %}
                    {% endwith %}                 
                                            
                    <form  method="POST" enctype="multipart/form-data">
                      {{ form.csrf_token }}
                        <div class="form-group row">
                          <div class="col-md-12">
                            {% if form.titre.errors %}
                            {{ form.titre(class="form-control form-control is-invalid", placeholder="Titre de la publication")}}
                            <div class="invalid-feedback">
                                {% for error in form.titre.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.titre(class="form-control", placeholder="Titre de la publication")}}
                            {% endif %}
                          </div>
                        </div>


                        <div class="form-group row">
                          <div class="col-md-12">
                            {% if form.resume.errors %}
                                        {{ form.resume(id="summernote",cols="30",rows="40")}}
                                        <i class="form-group__bar"></i>
                                        <div class="invalid-feedback">
                                            {% for error in form.resume.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                        {% else %}
                                        {{ form.resume(id="summernote",cols="30",rows="40")}}
                                        <i class="form-group__bar"></i>
                                        {% endif %}
                          </div>
                        </div>
                        
                        <div class="form-group row">
                          <div class="col-md-6">
                            <div class="form-group">
                              <label class="control-label mb-1" > <small>Image de l'article en jpg et png</small> </label>
                              {% if form.image_article.errors %}
                              {{ form.image_article(class="form-control is-invalid")}}
                              <i class="form-group__bar"></i>
                              <div class="invalid-feedback">
                                  {% for error in form.image_article.errors %}
                                      <span>{{ error }}</span>
                                  {% endfor %}
                              </div>
                              {% else %}
                              {{ form.image_article(class="form-control")}}
                              <i class="form-group__bar"></i>
                              {% endif %}
                          </div>
                          </div>
                          <div class="col-md-6">
                            <div class="form-group">
                              <label class="control-label mb-1" > <small>Document PDF</small> </label>
                              {% if form.pdf_document.errors %}
                              {{ form.pdf_document(class="form-control is-invalid")}}
                              <i class="form-group__bar"></i>
                              <div class="invalid-feedback">
                                  {% for error in form.pdf_document.errors %}
                                      <span>{{ error }}</span>
                                  {% endfor %}
                              </div>
                              {% else %}
                              {{ form.pdf_document(class="form-control")}}
                              <i class="form-group__bar"></i>
                              {% endif %}
                          </div>
                          </div>
                        </div>

                        <div class="form-group row">
                          <div class="col-md-6">
                            <label> <i class="fa fa-youtube"></i> Lien Youtube</label>
                            {% if form.url.errors %}
                            {{ form.url(class="form-control form-control is-invalid", placeholder="URL Youtube")}}
                            <div class="invalid-feedback">
                                {% for error in form.url.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.url(class="form-control", placeholder="URL Youtube")}}
                            {% endif %}
                          </div>
                          <div class="col-md-6">
                            <label class="control-label mb-1" > <small>Catégorie</small> </label>
                            {% if form.categorie.errors %}
                            {{ form.categorie(class="choices form-select")}}
                            <div class="invalid-feedback">
                                {% for error in form.categorie.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.categorie(class="choices form-select")}}    
                            {% endif %}
                          </div>
                        </div>



                        <div class="text-center mb-1">
                            <button class="btn btn-outline-success btn-md"  type="submit">
                               Enregistrer
                            </button>
                            <a class="btn btn-danger " id="success" href="{{url_for('publication.index')}}  ">Annuler</a>     
                        </div>
                      </form>
                  </div><!--/card-block-->
                </div><!-- /form card login -->
              </div>
            </div>
          </div><!--/col-->
  </div><!--/row-->

{% endblock body %}


{%block jsblock%}
   <script src="{{url_for('static', filename='nv_admin/vendors/choices.js/choices.min.js')}}"></script>
   <script src="{{url_for('static', filename='nv_admin/vendors/jquery/jquery.min.js')}}"></script>
   <script src="{{url_for('static', filename='nv_admin/vendors/summernote/summernote-lite.min.js')}}"></script>
   <script>
       $('#summernote').summernote({
           tabsize: 2,
           height: 120,
       });
   </script>
{%endblock%}




   

app/templates/publication/editim.html
    {% extends "layout/admini.html" %}


    {% block body %}
    <div class="row">
      <div class="col-12 col-md-6 order-md-1 order-last">
          <h3>Publications</h3>
      </div>
      <div class="col-12 col-md-6 order-md-2 order-first">
          <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{url_for('main.dashboard')}}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{url_for('publication.index')}}">Les publications</a></li>
                <li class="breadcrumb-item active" aria-current="page">Modification image</li>
              </ol>
          </nav>
      </div>
  </div>

        <div class="row">
          <div class="col-md-12 mt-5"> 
            <div class="row">
              <div class="col-md-8">
                <div class="card card-outline-secondary box-shadow--3dp">
                  <div class="card-body">
                    <h3><b>Modification de l'image de la publication</b></h3> 
                    <small> {{titre}} </small>
                    <br>
                    {% with messages= get_flashed_messages(with_categories=true) %}
                    {% if messages  %}
                        {% for category, message in messages %}
                            <div class="alert text-center alert-{{ category }}">
                                <b>{{ message }}</b>
                            </div>
                        {% endfor %}
                    {% endif %}
                    {% endwith %}           
                                            
                    <form  method="POST" enctype="multipart/form-data">
                      {{ form.csrf_token }}

                        <div class="form-group row">
                          <div class="col-md-12">
                            <div class="form-group">
                              <label class="control-label mb-1" > <small>Image de l'article en jpg et png</small> </label>
                              {% if form.image_article.errors %}
                              {{ form.image_article(class="form-control is-invalid")}}
                              <i class="form-group__bar"></i>
                              <div class="invalid-feedback">
                                  {% for error in form.image_article.errors %}
                                      <span>{{ error }}</span>
                                  {% endfor %}
                              </div>
                              {% else %}
                              {{ form.image_article(class="form-control")}}
                              <i class="form-group__bar"></i>
                              {% endif %}
                          </div>
                          </div>

                        </div>

                        <div class="text-center mb-1">
                            <button class="btn btn-primary btn-min-width mr-1 mb-1" id="submit" name="submit" type="submit">
                                <i class="la la-folder-o"></i> Modifier
                            </button>
                            <a class="btn btn-danger " href="{{url_for('publication.index')}}  ">Annuler</a>     
                        </div>
                      </form>
                  </div><!--/card-block-->
                </div><!-- /form card login -->
              </div>
            </div>
          </div><!--/col-->
        </div><!--/row-->

    {% endblock body %}


    {%block jsblock%}
        <script>    
          $('#summernote').summernote({
          height: 300,                 // set editor height
          minHeight: null,             // set minimum height of editor
          maxHeight: null,             // set maximum height of editor
          focus: true                  // set focus to editable area after initializing summernote
          });
      
          $(document).ready(function() {
          $('.js-example-basic-single').select2();
          $('.js-example-basic-singled').select2();
          });
      </script>
   
    {%endblock%}

app/templates/publication/index.html
{% extends "layout/admini.html" %}
{% block summurnote %}
<style>
    img {
        max-width: 100%;
        max-height: 100%;
    }
</style>
{%endblock%}

{% block body %}
<div class="row">
    <div class="col-12 col-md-6 order-md-1 order-last">
        <h3>Publications</h3>
        <br>
        <a href="{{url_for('publication.ajouter')}} " class="d-none d-md-inline-block btn btn-md btn-primary shadow-md">
        <i class="fa fa-file-o fa-md text-white-50"></i> Ajouter publication</a>
    </div>
    <div class="col-12 col-md-6 order-md-2 order-first">
        <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{url_for('main.dashboard')}}">Dashboard</a></li>
                <li class="breadcrumb-item active" aria-current="page">Liste des publications</li>
            </ol>
        </nav>
    </div>
</div>




<div class="row">
    <div class="col-md-12">
        <br>
        {% with messages= get_flashed_messages(with_categories=true) %}
                    {% if messages  %}
                        {% for category, message in messages %}
                            <div class="alert text-center alert-{{ category }}">
                                <b>{{ message }}</b>
                            </div>
                        {% endfor %}
                    {% endif %}
                    {% endwith %}
        <br>
    </div>
</div>
<div class="row">
    {%if taille>0 %}
    {%for listes in liste%}
    <div class="col-lg-4 mb-4">
        <div class="card box-shadow--3dp">
            {%if listes.url_img !=None%}
            <div class="paysage">
                <img src="{{url_for('static', filename='publication/{}'.format(listes.url_img))}} " alt="" height="215"
                    width="367" class="card-img-top img-fluid">
            </div>
            {%endif%}
            <div class="card-body">
                <h5 class="card-title"> {{listes.titre}} </h5>
                <div class="card-text">
                    <div class="text-left">
                        <div class="divider divider-left">
                            <div class="divider-text">Modification & Statistique</div>
                        </div>
                        <a data-bs-toggle="tooltip" data-bs-placement="top" title="Editer" href="{{url_for('publication.edit', pub_id=listes.id)}} "
                            class="btn btn-outline-success btn-sm">Editer</a>
                        <a data-bs-toggle="tooltip" data-bs-placement="top" title="Editer img" href="{{url_for('publication.edit_image', pub_id=listes.id)}}"
                            class="btn btn-outline-warning btn-sm"><i class="bi bi-camera"></i></a>
                        <a data-bs-toggle="tooltip" data-bs-placement="top" title="Editer pdf"  href="{{url_for('publication.edit_pdf', pub_id=listes.id)}}" class="btn btn-outline-info btn-sm"><i class="bi bi-file-earmark"></i></a>
                        
                        {%if listes.statut==True%}
                        <a data-bs-toggle="tooltip" data-bs-placement="top" title="Activer"  class="btn btn-outline-success btn-sm" href="{{url_for('publication.statut', pub_id=listes.id)}}"><i class="bi bi-unlock"
                                aria-hidden="true"></i></a>
                        {%else%}
                        <a data-bs-toggle="tooltip" data-bs-placement="top" title="Désactiver"  class="btn btn-outline-danger btn-sm" href="{{url_for('publication.statut', pub_id=listes.id)}}"><i class="bi bi-lock"
                                aria-hidden="true"></i></a>
                        {%endif%}
                        
                        {%if listes.pred_jour==True and listes.cat_pub.nom=='Prédications' %}
                        <a data-bs-toggle="tooltip" data-bs-placement="top" title="Activer"  class="btn btn-outline-dark btn-sm" href="{{url_for('publication.alune', pub_id=listes.id)}}"><i class="fa fa-certificate"
                                aria-hidden="true"></i></a>
                        {%elif listes.pred_jour==False and listes.cat_pub.nom=='Prédications' %}
                        <a data-bs-toggle="tooltip" data-bs-placement="top" title="Désactiver"  class="btn btn-outline-warning btn-sm" href="{{url_for('publication.alune', pub_id=listes.id)}}"><i class="fa fa-circle"
                                aria-hidden="true"></i></a>
                        {%endif%}

                        
                    </div>
                    <br>
                    <div class="d-flex flex-row-reverse">
                        <a href="" class="btn btn-danger btn-sm"><i class="bi bi-hand-thumbs-up-fill"></i> <span
                                class="badge bg-transparent"> {{listes.nbr_like}} </span> </a>
                        <a href="" class="btn btn-warning btn-sm"><i class="bi bi-eye-fill"></i> <span
                                class="badge badge-pill badge-danger"> {{listes.nbr_lu}} </span> </a>
                        <a href="" class="btn btn-dark btn-sm"><i class="bi bi-chat-right-text"></i> <span
                                class="badge badge-pill badge-info"> {{listes.nbr_cmt}} </span> </a>
                    </div>
                </div>

                <div class="divider divider-right">
                    <div class="divider-text">{{listes.cat_pub.nom}}</div>
                </div>
                <div class="card-text ">

                    <div class="d-flex">
                        <div class="p-2"><a href="#" class="card-link justify-content-left">{{listes.user_pub.prenom}} </a>
                    
                        </div>
                        
                        <div class="ml-auto p-2">{%if listes.date_pub==listes.date_mod%}
                            <a href="#" class="card-link justify-content-right">Ajouter le {{listes.date_pub.strftime('%d-%m-%Y')}} </a>
                            {%else%}
                            <a href="#" class="card-link justify-content-right">Modifier {{listes.date_mod.strftime('%d-%m-%Y')}} </a>
                            {%endif%}</div>
                      </div>

                        
                    
                    
                    

                </div>

            </div>
        </div>
    </div>
    {%endfor%}
    {%else%}
    <p class="text-center" style="margin-top:150px">
        <i class="fa fa-file-o success fa-5x text-center"></i>
        <h4 class="text-center">AUCUNE PUBLICATION .</h4>
        <br><br><br>
      </p>
    {%endif%}
</div>
{% endblock body %}

{%block jsblock%}

<script>
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl)
    })
</script>

{%endblock%}