app/rubrique/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField, SelectField, IntegerField, DecimalField
from wtforms.validators import DataRequired, Length,Email, EqualTo, ValidationError
from wtforms.ext.sqlalchemy.fields import QuerySelectField

from ..models import Rubrique


class AjoutRubForm(FlaskForm):
    nom= StringField('Nom', validators=[DataRequired("Completer nom"),  Length(min=4, max=32, message="Veuillez respecté les caractères")])
    resume=TextAreaField('Resume', validators=[DataRequired("Completer le resumé")])
    image_rubrique=FileField('Image', validators=[DataRequired("Image en JPG svp "), FileAllowed(['jpg'],'Seul jpg est autorisé')])
    submit = SubmitField('Categorie')

    #Fornction de verification d'unique existenace dans la base des données
    def validate_nom(self, nom):
        type= Rubrique.query.filter_by(nom=nom.data).first()
        if type:
            raise ValidationError("Cette rubrique existe déjà")


class EditRubForm(FlaskForm):
    nom= StringField('Nom', validators=[DataRequired("Completer nom"),  Length(min=4, max=32, message="Veuillez respecté les caractères")])
    resume=TextAreaField('Resume', validators=[DataRequired("Completer le resumé")])
    image_rubrique=FileField('Image', validators=[FileAllowed(['jpg'],'Seul jpg est autorisé')])
    submit = SubmitField('Categorie')

app/rubrique/__init__.py
from flask import Blueprint

rubrique = Blueprint('rubrique', __name__, url_prefix='/rubrique')
# never forget 
from . import routes

app/rubrique/routes.py
from flask import render_template, flash, url_for, redirect, request, session
from wtforms.fields.core import LocaleAwareNumberField
from .. import db, bcrypt
from ..models import Rubrique
from app.rubrique.forms import AjoutRubForm, EditRubForm
from app.rubrique.upload import rubrique_image
from flask_login import login_user, current_user, logout_user, login_required
from ..utilites.utility import title_page, webmaster_admin, admin
from . import rubrique



''' Ajoute une rubrique de donation '''

@rubrique.route('/ajouter', methods=['GET','POST'])
@login_required
@admin
def ajoutrub():
   title='Rubrique'
   #formulaire
   form=AjoutRubForm()
   if form.validate_on_submit():
      nom_cat=form.nom.data
      im_phot=rubrique_image(form.image_rubrique.data)
      #Requete de verification de la rubrique
      rubrique_enre=Rubrique(nom=nom_cat, image_rubrique=im_phot, resume=form.resume.data)
      db.session.add(rubrique_enre)
      db.session.commit()
      flash("Ajout avec succès",'success')
      return redirect(url_for('rubrique.index')) 

   return render_template('rubrique/ajouter.html',  title=title, form=form)



""" Liste de catégorie """

@rubrique.route('/liste', methods=['GET', 'POST'])
@login_required
@admin
def index():
   #Titre
   title=title_page('Rubrique')
   #Requête d'affichage des rubriques
   listes=Rubrique.query.order_by(Rubrique.id.desc()).all()

   return render_template('rubrique/index.html',title=title, liste=listes)

""" Modifier statut de l'Utilisateur """
@rubrique.route('/statut/<int:rub_id>', methods=['GET', 'POST'])
@login_required
@admin
def statut(rub_id):
   #Titre
   title=title_page('Catégorie')
   #Requête de vérification de la rubrique
   cat_statu=Rubrique.query.filter_by(id=rub_id).first()

   if cat_statu is None:
      return redirect(url_for('rubrique.index'))

   if cat_statu.statut == True:
      cat_statu.statut=False
      db.session.commit()
      flash("La rubrique est désactivée sur la plateforme",'primary')
      return redirect(url_for('rubrique.index'))
   else:
      cat_statu.statut=True
      db.session.commit()
      flash("La rubrique est activée sur la plateforme",'primary')
      return redirect(url_for('rubrique.index'))
   
   return render_template('rubrique/index.html',title=title)


# """ Modification de la rubrique  """

@rubrique.route('/edit_<int:rub_id>', methods=['GET', 'POST'])
@login_required
@admin
def edit(rub_id):

   form=EditRubForm()
   #Titre
   title=title_page('Rubrique')
   #Requête de vérification du type
   rub_class=Rubrique.query.filter_by(id=rub_id).first_or_404()
   #Le nom du type encours de modification
   if form.validate_on_submit(): 
      rub_class.nom=form.nom.data
      if form.image_rubrique.data is not None:
         rub_class.image_rubrique=rubrique_image(form.image_rubrique.data)
      rub_class.resume=form.resume.data
      db.session.commit()
      flash("Modification réussie",'success')
      return redirect(url_for('rubrique.index'))
      
   if request.method=='GET':
      form.nom.data=rub_class.nom
      form.resume.data=rub_class.resume
      
   return render_template('rubrique/edit.html', form=form, title=title, image_rub=rub_class.image_rubrique)

app/templates/rubrique/ajouter.html
{% extends "layout/admini.html" %}
{% block css %}
<link rel="stylesheet" href="{{url_for('static', filename='nv_admin/vendors/choices.js/choices.min.css')}}" />
<link rel="stylesheet" href="{{url_for('static', filename='nv_admin/vendors/summernote/summernote-lite.min.css')}}" >
{%endblock%}

{% block body %}

    <div class="row">
      <div class="col-12 col-md-6 order-md-1 order-last">
          <h3>Rubrique de dons</h3>
      </div>
      <div class="col-12 col-md-6 order-md-2 order-first">
          <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{url_for('main.dashboard')}}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{url_for('rubrique.index')}}">Les rubriques</a></li>
                <li class="breadcrumb-item active" aria-current="page">Ajouter rubrique</li>
              </ol>
          </nav>
      </div>
  </div>
<br>
  <div class="row">
          <div class="col-md-12"> 
            <div class="row">
              <div class="col-md-7">
                <div class="card card-outline-secondary box-shadow--3dp">
                  <div class="card-body">
                    <h3><b>Ajouter une rubrique</b></h3> <br>
                    {% with messages= get_flashed_messages(with_categories=true) %}
                    {% if messages  %}
                        {% for category, message in messages %}
                            <div class="alert text-center alert-{{ category }}">
                                <b>{{ message }}</b>
                            </div>
                        {% endfor %}
                    {% endif %}
                    {% endwith %}                 
                       
                    <form  method="POST" enctype="multipart/form-data">
                      {{ form.csrf_token }}
    
                        <div class="form-group row">
                          <div class="col-md-12">
                            {% if form.nom.errors %}
                            {{ form.nom(class="form-control form-control is-invalid", placeholder="Nom de la rubrique")}}
                            <div class="invalid-feedback">
                                {% for error in form.nom.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.nom(class="form-control", placeholder="Nom de la rubrique")}}
                            {% endif %}
                          </div>
                        </div>
                        <div class="form-group row">
                          <div class="col-md-12">
                            {% if form.resume.errors %}
                                        {{ form.resume(id="summernote",cols="30",rows="40")}}
                                        <i class="form-group__bar"></i>
                                        <div class="invalid-feedback">
                                            {% for error in form.resume.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                        {% else %}
                                        {{ form.resume(id="summernote",cols="30",rows="40")}}
                                        <i class="form-group__bar"></i>
                                        {% endif %}
                          </div>
                        </div>
                        <div class="form-group row">
                          <div class="col-md-6">
                            <div class="form-group">

                              <label class="control-label mb-1" > <small>Image de la rubrique en jpg</small> </label>
                              {% if form.image_rubrique.errors %}
                              {{ form.image_rubrique(class="form-control is-invalid")}}
                              <i class="form-group__bar"></i>
                              <div class="invalid-feedback">
                                  {% for error in form.image_rubrique.errors %}
                                      <span>{{ error }}</span>
                                  {% endfor %}
                              </div>
                              {% else %}
                              {{ form.image_rubrique(class="form-control")}}
                              <i class="form-group__bar"></i>
                              {% endif %}
                          </div>
                          </div>
                        </div>

                        <div class="text-center mb-1">
                            <button class="btn btn-outline-success btn-md"  type="submit">
                               Enregistrer
                            </button>
                            <a class="btn btn-danger " id="success" href="{{url_for('rubrique.index')}}  ">Annuler</a>     
                        </div>
                    </form>
                  </div><!--/card-block-->
                </div><!-- /form card login -->
              </div>
            </div>
          </div><!--/col-->
  </div><!--/row-->

{% endblock body %}

{%block jsblock%}
   <script src="{{url_for('static', filename='nv_admin/vendors/choices.js/choices.min.js')}}"></script>
   <script src="{{url_for('static', filename='nv_admin/vendors/jquery/jquery.min.js')}}"></script>
   <script src="{{url_for('static', filename='nv_admin/vendors/summernote/summernote-lite.min.js')}}"></script>
   <script>
       $('#summernote').summernote({
           tabsize: 2,
           height: 120,
       });
   </script>
{%endblock%}

app/templates/rubrique/edit.html
{% extends "layout/admini.html" %}
{% block css %}
<link rel="stylesheet" href="{{url_for('static', filename='nv_admin/vendors/choices.js/choices.min.css')}}" />
<link rel="stylesheet" href="{{url_for('static', filename='nv_admin/vendors/summernote/summernote-lite.min.css')}}" >
{%endblock%}
{% block body %}
<div class="row">
  <div class="col-12 col-md-6 order-md-1 order-last">
      <h3>Rubrique de dons</h3>
  </div>
  <div class="col-12 col-md-6 order-md-2 order-first">
      <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{url_for('main.dashboard')}}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{{url_for('rubrique.index')}}">Les rubriques</a></li>
            <li class="breadcrumb-item active" aria-current="page">Modifier rubrique</li>
          </ol>
      </nav>
  </div>
</div>
<br>
  <div class="row">
          <div class="col-md-12"> 
            <div class="row">
              <div class="col-md-7">
                <div class="card card-outline-secondary box-shadow--3dp">
                  <div class="card-body">
                    <h3><b>Modifier {{cate_nom}} </b></h3> <br>
                    {% with messages= get_flashed_messages(with_categories=true) %}
                    {% if messages  %}
                        {% for category, message in messages %}
                            <div class="alert text-center alert-{{ category }}">
                                <b>{{ message }}</b>
                            </div>
                        {% endfor %}
                    {% endif %}
                    {% endwith %}                 
                                            
                    <form  method="POST" enctype="multipart/form-data">
                      {{ form.csrf_token }}
    
                        <div class="form-group row">
                          <div class="col-md-12">
                            {% if form.nom.errors %}
                            {{ form.nom(class="form-control form-control is-invalid", placeholder="Nom de la rubrique")}}
                            <div class="invalid-feedback">
                                {% for error in form.nom.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.nom(class="form-control", placeholder="Nom de la rubrique")}}
                            {% endif %}
                          </div>
                        </div>
                        <div class="form-group row">
                          <div class="col-md-12">
                            {% if form.resume.errors %}
                                        {{ form.resume(id="summernote",cols="30",rows="40")}}
                                        <i class="form-group__bar"></i>
                                        <div class="invalid-feedback">
                                            {% for error in form.resume.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                        {% else %}
                                        {{ form.resume(id="summernote",cols="30",rows="40")}}
                                        <i class="form-group__bar"></i>
                                        {% endif %}
                          </div>
                        </div>
                        <div class="form-group row">
                          <div class="col-md-6">
                            <img src="{{url_for('static', filename='rubrique/{}'.format(image_rub))}}" height="40" width="40" alt="">
                           
                            <div class="form-group">
                              <label class="control-label mb-1" > <small>Image de la rubrique en jpg</small> </label>
                              {% if form.image_rubrique.errors %}
                              {{ form.image_rubrique(class="form-control is-invalid")}}
                              <i class="form-group__bar"></i>
                              <div class="invalid-feedback">
                                  {% for error in form.image_rubrique.errors %}
                                      <span>{{ error }}</span>
                                  {% endfor %}
                              </div>
                              {% else %}
                              {{ form.image_rubrique(class="form-control")}}
                              <i class="form-group__bar"></i>
                              {% endif %}
                          </div>
                          </div>
                        </div>

                        <div class="text-center mb-1">
                            <button class="btn btn-outline-success btn-md"  type="submit">
                               Modifier
                            </button>
                            <a class="btn btn-danger " id="success" href="{{url_for('rubrique.index')}}  ">Annuler</a>     
                        </div>
                    </form>
                  </div><!--/card-block-->
                </div><!-- /form card login -->
              </div>
            </div>
          </div><!--/col-->
  </div><!--/row-->

{% endblock body %}
{%block jsblock%}
   <script src="{{url_for('static', filename='nv_admin/vendors/choices.js/choices.min.js')}}"></script>
   <script src="{{url_for('static', filename='nv_admin/vendors/jquery/jquery.min.js')}}"></script>
   <script src="{{url_for('static', filename='nv_admin/vendors/summernote/summernote-lite.min.js')}}"></script>
   <script>
       $('#summernote').summernote({
           tabsize: 2,
           height: 120,
       });
   </script>
{%endblock%}

app/templates/rubrique/editd.html
{% extends "layout/admin.html" %}
{% block body %}
    <div class="row">
      <div class="col-md-12 mt-5"> 
        <div class="row justify-content-center">
          <div class="col-md-6">
            <div class="card card-outline-secondary box-shadow--3dp">
              <div class="card-body">
                <h3><b>Modifier la catégorie</b></h3> <br>
                
                                        {% with messages= get_flashed_messages(with_categories=true) %}
                                        {% if messages  %}
                                        {% for category, message in messages %}
                                        {%if category!="danger"%}
                                            <div class="alert round bg-{{ category }} alert-icon-left alert-dismissible mb-2" role="alert">
                                                <span class="alert-icon">
                                                    <i class="ft-thumbs-up"></i>
                                                </span>
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                                <strong>{{ message }}!</strong> 
                                                
                                            </div>
                                        {%else%}
                                            <div class="alert round bg-{{ category }} alert-icon-left alert-dismissible mb-2" role="alert">
                                                <span class="alert-icon">
                                                    <i class="ft-thumbs-down"></i>
                                                </span>
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                                <strong>{{ message }}!</strong>
                                                
                                            </div>
                                        {%endif%}
                                        
                                        {% endfor %}
                                        {% endif %}
                                        {% endwith %}
                <form class="user" method="POST">
                  {{ form.csrf_token }}
                    <div class="form-group row">
                      <div class="col-md-12">
                        
                        {% if form.nom.errors %}
                        {{ form.nom(class="form-control form-control form-control-user input-md is-invalid", placeholder="Nom de la catégorie")}}
                        <div class="invalid-feedback">
                            {% for error in form.nom.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ form.nom(class="form-control form-control form-control-user input-md", placeholder="Nom de la catégorie")}}
                        {% endif %}
                      </div>
                    </div>

                    <div class="text-center mb-1">
                        <button class="btn btn-success btn-min-width mr-1 mb-1" id="submit" name="submit" type="submit">
                            <i class="la la-folder-o"></i> Modifier
                        </button>
                        <a class="btn btn-danger " href="{{url_for('categorie.index')}}  ">Annuler</a>     
                    </div>
                  </form>
              </div><!--/card-block-->
            </div><!-- /form card login -->
          </div>
        </div>
      </div><!--/col-->
    </div><!--/row-->
{% endblock body %}

app/templates/rubrique/index.html
{% extends "layout/admini.html" %}
{% block body %}

<div class="row">
  <div class="col-12 col-md-6 order-md-1 order-last">
      <h3>Rubrique des dons</h3>
      <br>
      <a href="{{url_for('rubrique.ajoutrub')}} " class="d-none d-md-inline-block btn btn-md btn-primary shadow-md">
      <i class="fa fa-folder-o fa-md text-white-50"></i> Ajouter rubrique</a>
  </div>
  <div class="col-12 col-md-6 order-md-2 order-first">
      <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
          <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{{url_for('main.dashboard')}}">Dashboard</a></li>
              <li class="breadcrumb-item active" aria-current="page">Liste des rubriques</li>
          </ol>
      </nav>
  </div>
</div>
<br><br>



  <div class="row" id="basic-table">
    

    <div class="col-12 col-md-7">
        {%if liste !=[]%} 
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Liste des rubriques</h3>
            </div>

                <div class="card-body">
                    <p class="card-text">
                        {% with messages= get_flashed_messages(with_categories=true) %}
                        {% if messages  %}
                            {% for category, message in messages %}
                                <div class="alert text-center alert-{{ category }}">
                                    <b>{{ message }}</b>
                                </div>
                            {% endfor %}
                        {% endif %}
                        {% endwith %}       
                    </p>
                    <!-- Table with outer spacing -->
                    <div class="table-responsive">
                        <table class="table table-lg">
                            <thead>
                                <tr>
                                  <th>Avatar</th>
                                  <th>Nom rubrique</th>
                                  <th class="text-center">Statut </th>
                                  <th class="text-center">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                              {%for categorie in liste%}
                              <tr>
                                <td><img src="{{url_for('static', filename='rubrique/{}'.format(categorie.image_rubrique))}} " alt="" height="40" width="50"></td>
                                <td> {{categorie.nom}} </td>
                                <td class="text-center">
                                  {%if categorie.statut==True%}
                                  <a href="{{url_for('rubrique.statut', rub_id=categorie.id)}}"><i class="fa fa-unlock" aria-hidden="true"></i></a>
                                  {%else%}
                                  <a href="{{url_for('rubrique.statut', rub_id=categorie.id)}}"><i class="fa fa-lock" aria-hidden="true"></i></a>
                                  {%endif%}
                                </td>
                                <td class="text-center"><a href="{{url_for('rubrique.edit', rub_id=categorie.id)}}"><i class="fa fa-edit" aria-hidden="true"></i></a></td>
                              </tr>
                              {%endfor%}
                            </tbody>
                        </table>
                    </div>
                </div>

        </div>
        {%else%}
          <p class="text-center" style="margin-top:100px">
            <i class="fa fa-folder success fa-5x text-center"></i>
            <h4 class="text-center">AUCUNE CATEGORIE .</h4>
            <br><br><br><br><br><br>
          </p>
        {%endif%}
    </div>

</div>




{% endblock body %}