app/media/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, RadioField,  PasswordField, SubmitField, BooleanField, TextAreaField, SelectField, IntegerField, DecimalField
from wtforms.validators import DataRequired, Length,Email, EqualTo, ValidationError,  url
from wtforms.fields.html5 import URLField
from wtforms.ext.sqlalchemy.fields import QuerySelectField

from ..models import Media


def rech_media():
    return Media.query.filter_by(statut=True).all()


class AjoutMediaForm(FlaskForm):
    titre= StringField('Titre', validators=[DataRequired("Completer le titre"),  Length(min=2, max=255, message="Veuillez respecté les caractères")])
    video = BooleanField()
    audio = BooleanField()
    mp_trois = FileField('mp3', validators=[FileAllowed(['mp3'],'Seul mp3 autorisé')])
    url = StringField('url')
    submit = SubmitField('Ajouter un media')


class EditMediaForm(FlaskForm):
    titre= StringField('Titre', validators=[DataRequired("Completer le titre"),  Length(min=2, max=255, message="Veuillez respecté les caractères")])
   
    submit = SubmitField('Modifier un media')


class EditVideoForm(FlaskForm):
    titre= StringField('Titre', validators=[DataRequired("Completer le titre"),  Length(min=2, max=255, message="Veuillez respecté les caractères")])
    url = StringField('url')
    submit = SubmitField('Modifier un media')

app/media/__init__.py
from flask import Blueprint

media = Blueprint('media', __name__, url_prefix='/media')
# never forget 
from . import routes

app/media/routes.py
import os
from flask import render_template, flash, url_for, redirect, request, session
from .. import db, bcrypt
from ..models import Media
from app.media.forms import AjoutMediaForm, EditMediaForm, EditVideoForm
#from app.evenement.upload import f_avatar
from flask_login import login_user, current_user, logout_user, login_required
from ..utilites.utility import title_page, message_historique, find_url
#from slugify import slugify
from . import media
import timeago
from datetime import datetime
from cloudinary.uploader import upload
from cloudinary.utils import cloudinary_url



''' Ajouter un media '''
@media.route('/ajouter', methods=['GET','POST'])
@login_required
def ajouter():
   title=title_page('Media')
   #formulaire
   form=AjoutMediaForm()

   if form.validate_on_submit():
      #Les variables de verifications des données
      ver_video=form.video.data
      ver_audio=form.audio.data
      enre_media=None
      message=None
      type_media=None
      url_video=None
      redirection=None
      
      print(ver_video,'dddddddddddddddddddddddddddddddddddddddddddd')

      if ver_video !=False or  find_url(form.url.data)==1 :
         if ver_video !=False:
            if find_url(form.url.data)==1:
               #Vérification de chaine de caractère
               if "watch?v=" in str(form.url.data):
                  url_video =str(form.url.data)
                  url_video = url_video.replace("watch?v=", "embed/")
                  enre_media=Media(titre=form.titre.data, type_media='Vidéo', url_media=url_video)
                  message=f"Enregistrement de l'url de la video {form.titre.data}"
                  type_media="Video"
               else:
                  enre_media=Media(titre=form.titre.data, type_media='Vidéo', url_media=form.url.data)
                  message=f"Enregistrement de l'url de la video {form.titre.data}"
                  type_media="Video"   
            else:
               flash("Le lien de la vidéo",'danger')
               return redirect(url_for('media.ajouter'))
         else:
            type_media="Audio"
            flash("Audio",'danger')
            return redirect(url_for('media.ajouter'))
                
      if ver_audio !=False or  form.mp_trois.data is not None:
         if ver_audio !=False:
            if form.mp_trois.data.filename !='':
               upload_result = upload(form.mp_trois.data, resource_type = "video")
               url_de_mp3=upload_result['url']
               enre_media=Media(titre=form.titre.data, type_media='Audio', url_media=url_de_mp3)
               message=f"Enregistrement de l'url de la video {form.titre.data}"
               type_media="Audio"
            else:
               flash("Charger la vidéo svp",'danger')
               return redirect(url_for('media.ajouter'))
         else:
            flash("Audio",'danger')
            return redirect(url_for('media.ajouter'))
      
      message_historique(message, user_ide=current_user.id)
      db.session.add(enre_media)
      db.session.commit()
      #Rédirection selon les médias
      if type_media=='Audio':
         return redirect(url_for('media.index_audio'))
      else:
         return redirect(url_for('media.index_video'))
         
   return render_template('media/ajouter.html',  title=title, form=form)


@media.route('/', methods=['GET', 'POST'])
@login_required
def index():

   #Titre
   title=title_page('Media')
   #Requête d'affichage des evenements
   listes=Media.query.order_by(Media.id.desc()).all()
   #Taille de evenements   
   taille=len(listes)

   return render_template('media/index.html',title=title, liste=listes, taille=taille)


#Rédirection selon le média audio
@media.route('/audio', methods=['GET', 'POST'])
@login_required
def index_audio():
   listes=Media.query.filter_by(type_media='Audio').order_by(Media.id.desc()).all()
   return render_template('media/index_audio.html', listes=listes)

#Rédirection selon le média video
@media.route('/video', methods=['GET', 'POST'])
@login_required
def index_video():
   listes=Media.query.filter_by(type_media='Vidéo').order_by(Media.id.desc()).all()
   return render_template('media/index_video.html', listes=listes)


@media.route('/edit_<int:media_id>', methods=['GET', 'POST'])
@login_required
def edit(media_id):
   #Modification
   form = EditMediaForm()
   #Titre
   title = title_page('Media')

   selec_media = Media.query.filter_by(id=media_id).first()
   
   if form.validate_on_submit():
       selec_media.titre=form.titre.data
       selec_media.type_media=form.type_media.data
       db.session.commit()
       #Enregistrement
       message=f"Modification du media :{form.titre.data}"
       message_historique(message)

       flash("Modification réussie",'primary')
       return redirect(url_for('media.index'))
      
   if request.method=='GET':
       form.titre.data=selec_media.titre
       form.type_media.data=selec_media.type_media
  

   return render_template('media/edit.html', form=form, title=title)

""" Modification statut """
@media.route('/statut/<int:media_id>', methods=['GET', 'POST'])
@login_required
def statut(media_id): 
   #Titre
   title=title_page('Media')
   #Requête de vérification du type
   selec_media=Media.query.filter_by(id=media_id).first_or_404()

   if selec_media is None:
      return redirect(url_for('media.index'))

   if selec_media.statut == True:
      selec_media.statut=False
      db.session.commit()
      flash("Ce media est désactivé sur la plateforme",'primary')
      return redirect(url_for('media.index'))
   else:
      selec_media.statut=True
      db.session.commit()
      flash("Ce media est activé sur la plateforme",'primary')
      return redirect(url_for('media.index'))   
   return render_template('media/index.html',title=title)



""" Suppression audio """
@media.route('/sup/<int:media_id>', methods=['GET', 'POST'])
@login_required
def sup_audio(media_id): 
   #Titre
   title=title_page('Media')
   #Requête de vérification du type
   selec_media=Media.query.filter_by(id=media_id).first_or_404()
   Media.query.filter_by(id=media_id).delete()
   db.session.commit()
   flash("L'audio est supprimée avec succès",'danger')
   return redirect(url_for('media.index_audio'))

""" Suppression vidéo """
@media.route('/sup/video/<int:media_id>', methods=['GET', 'POST'])
@login_required
def sup_video(media_id): 
   #Titre
   title=title_page('Media')
   #Requête de vérification du type
   selec_media=Media.query.filter_by(id=media_id).first_or_404()
   Media.query.filter_by(id=media_id).delete()
   db.session.commit()
   flash("La vidéo est supprimée avec succès",'danger')
   return redirect(url_for('media.index_video'))


@media.route('/audio/edit_<int:media_id>', methods=['GET', 'POST'])
@login_required
def edit_audio(media_id):
   #Modification
   form = EditMediaForm()
   #Titre
   title = title_page('Media')
   selec_media = Media.query.filter_by(id=media_id).first_or_404()
   if form.validate_on_submit():
       selec_media.titre=form.titre.data
       db.session.commit()
       #Enregistrement
       message=f"Modification du media :{form.titre.data}"
       message_historique(message, user_ide=current_user.id)
       flash("Modification réussie",'primary')
       return redirect(url_for('media.index_audio'))
   if request.method=='GET':
       form.titre.data=selec_media.titre
   return render_template('media/edit_audio.html', form=form, title=title)


@media.route('/video/edit_<int:media_id>', methods=['GET', 'POST'])
@login_required
def edit_video(media_id):
   #Modification
   form = EditVideoForm()
   #Titre
   title = title_page('Media')
   url_video=None
   
   selec_media = Media.query.filter_by(id=media_id).first_or_404()
   if form.validate_on_submit():
      if find_url(form.url.data)==1:
         if "watch?v=" in str(form.url.data):
            url_video =str(form.url.data)
            url_video = url_video.replace("watch?v=", "embed/")
         else:
            url_video=form.url.data
   
         selec_media.titre=form.titre.data
         selec_media.url_media=url_video
         db.session.commit()
         #Enregistrement
         message=f"Modification du media :{form.titre.data}"
         message_historique(message, user_ide=current_user.id)
         flash("Modification réussie",'primary')
         return redirect(url_for('media.index_video'))
   if request.method=='GET':
      form.titre.data=selec_media.titre
      form.url.data=selec_media.url_media
   return render_template('media/edit_video.html', form=form, title=title)


""" Modification statut """
@media.route('/audio/statut/<int:media_id>', methods=['GET', 'POST'])
@login_required
def statut_audio(media_id): 
   #Titre
   title=title_page('Media')
   #Requête de vérification du type
   selec_media=Media.query.filter_by(id=media_id).first_or_404()

   if selec_media is None:
      return redirect(url_for('media.index_audio'))

   if selec_media.statut == True:
      selec_media.statut=False
      db.session.commit()
      flash("Ce media est désactivé sur la plateforme",'primary')
      return redirect(url_for('media.index_audio'))
   else:
      selec_media.statut=True
      db.session.commit()
      flash("Ce media est activé sur la plateforme",'primary')
      return redirect(url_for('media.index_audio'))

   return render_template('media/index.html',title=title)



""" Modification statut """
@media.route('/video/statut/<int:media_id>', methods=['GET', 'POST'])
@login_required
def statut_video(media_id): 
   #Titre
   title=title_page('Media')
   #Requête de vérification du type
   selec_media=Media.query.filter_by(id=media_id).first_or_404()

   if selec_media is None:
      return redirect(url_for('media.index_video'))

   if selec_media.statut == True:
      selec_media.statut=False
      db.session.commit()
      flash("Ce media est désactivé sur la plateforme",'primary')
      return redirect(url_for('media.index_video'))
   else:
      selec_media.statut=True

app/templates/media/ajouter.html
{% extends "layout/admini.html" %}
{% block css %}
<link rel="stylesheet" href="{{url_for('static', filename='nv_admin/vendors/choices.js/choices.min.css')}}" />
{%endblock%}


{% block body %}
<div class="row">
  <div class="col-12 col-md-6 order-md-1 order-last">
      <h3>Média</h3>
  </div>
  <div class="col-12 col-md-6 order-md-2 order-first">
      <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{url_for('main.dashboard')}}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="">Les médias</a></li>
            <li class="breadcrumb-item active" aria-current="page">Ajouter une média</li>
          </ol>
      </nav>
  </div>
</div>

    <div class="row">
      <div class="col-md-12"> 
        <div class="row">
          <div class="col-md-7">
            <div class="card card-outline-secondary box-shadow--3dp">
              <div class="card-body">
                <h3><b>Ajouter une média</b></h3> <br>
                {% with messages= get_flashed_messages(with_categories=true) %}
                {% if messages  %}
                    {% for category, message in messages %}
                        <div class="alert text-center alert-{{ category }}">
                            <b>{{ message }}</b>
                        </div>
                    {% endfor %}
                {% endif %}
                {% endwith %}                 
                                        
                <form  method="POST" enctype="multipart/form-data">
                  {{ form.csrf_token }}
                  <div class="row">
                    <div class="col-md-12">
                    <div class="form-group position-relative has-icon-left">
                      {% if form.titre.errors %}
                      {{ form.titre(class="form-control is-invalid", placeholder="Titre du média")}}
                      <div class="invalid-feedback">
                          {% for error in form.titre.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                      {% else %}
                      {{ form.titre(class="form-control", placeholder="Titre du média")}}
                      {% endif %}

                      <div class="form-control-icon">
                          <i class="bi bi-pen"></i>
                      </div>
                    </div>
                  </div>
                  </div>
                  <div class="row">
                    <div class="form-group row">
                      <div class="col-md-6">
                        <ul class="list-unstyled mb-0">
                          <span id="a">
                          
                          <li class="d-inline-block me-2 mb-1">
                              <div class="form-check" >
                                  <div class="custom-control custom-checkbox">
                                      {{ form.audio(id="customColorCheck1", class="form-check-input form-check-secondary", )}}
                                      <label class="form-check-label" for="customColorCheck1">Choir l'audio</label>
                                  </div>
                              </div>
                          </li>
                        </span>
                        <span id="v">
                          <li class="d-inline-block me-2 mb-1" id="v">
                              <div class="form-check">
                                  <div class="custom-control custom-checkbox">
                                      {{ form.video(id="customColorCheck2", class="form-check-input form-check-secondary",)}}
                                      <label class="form-check-label" for="customColorCheck2">Choisir la video</label>
                                  </div>
                              </div>
                          </li>
                        </span>
                      </ul>
                      </div>
                    </div>
                  </div>
                  
                  <div class="row" id="div_deux">
                    <div class="col-md-12">
                    <div class="form-group position-relative has-icon-left">
                      <small>URL du video *</small>
                      {% if form.url.errors %}
                      {{ form.url(class="form-control is-invalid", placeholder="URL Vidéo")}}
                      <div class="invalid-feedback">
                          {% for error in form.url.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                      {% else %}
                      {{ form.url(class="form-control", placeholder="URL Video")}}
                      {% endif %}

                      <div class="form-control-icon">
                          <i class="fa fa-youtube-square"></i>
                      </div>
                    </div>
                  </div>
                  </div>

                  <div class="row" id="div_un">
                    <div class="col-md-6">
                      <div class="form-group">
                        <div class="mt-2">
                          <small>Fichier mp3 *</small>
                          {% if form.mp_trois.errors %}
                          {{ form.mp_trois(class="form-control-file")}}
                          <div class="invalid-feedback">
                              {% for error in form.mp_trois.errors %}
                                  <span>{{ error }}</span>
                              {% endfor %}
                          </div>
                          {% else %}
                          {{ form.mp_trois(class="form-control-file")}}
                          {% endif %}
                        </div>
                      </div>
                    </div>
                  </div>
                    <div class="text-center mb-1">
                        <button class="btn btn-outline-success btn-md"  type="submit">
                           Enregistrer
                        </button>
                        <a class="btn btn-danger " id="success" href="{{url_for('main.dashboard')}}  ">Annuler</a>     
                    </div>
                  </form>
              </div><!--/card-block-->
            </div><!-- /form card login -->
          </div>
        </div>
      </div><!--/col-->
    </div><!--/row-->
{% endblock body %}

{%block jsblock%}
<script src="{{url_for('static', filename='plugins/jquery-3.3.1.min.js')}}"></script>
<script>
  $("#div_un").hide();
  $("#div_deux").hide();


  $(function () {
      $("#customColorCheck1").click(function () {
        $("#a").hide();
        $("#v").show();
        $("#div_deux").hide();
        $("#div_un").show();
        $('#customColorCheck2').prop('checked', false);
        $('#customColorCheck1').prop('checked', true);
        
      });
      $("#customColorCheck2").click(function () {
        $("#v").hide();
        $("#a").show();
        $("#div_un").hide();
        $("#div_deux").show();
        $('#customColorCheck1').prop('checked', false);
        $('#customColorCheck2').prop('checked', true);
        
        

      });
  });
</script>
{%endblock%}

app/templates/media/index.html
{% extends "layout/admin.html" %}
{% block body %}


<div class="row">
    <div class="col-md-12 mt-5"> 
      <div class="row justify-content-center">
        <div class="col-md-12">
          
          <div class="card card-outline-secondary box-shadow--3dp">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <h3><b>Liste des medias</b></h3>
                    </div>
                    <div class="col-md-6 text-right">
                        <a class="btn btn-primary" href="{{url_for('media.ajouter')}}  ">Ajouter</a>
                    </div>
                
                </div>
                <br><br>
                                      {% with messages= get_flashed_messages(with_categories=true) %}
                                      {% if messages  %}
                                      {% for category, message in messages %}
                                      {%if category!="danger"%}
                                          <div class="alert round bg-{{ category }} alert-icon-left alert-dismissible mb-2" role="alert">
                                              <span class="alert-icon">
                                                  <i class="fa fa-thumbs-o-down"></i>
                                              </span>
                                              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                  <span aria-hidden="true">&times;</span>
                                              </button>
                                              <strong class="text-gray-900">{{ message }}!</strong> 
                                              
                                          </div>
                                      {%else%}
                                          <div class="alert round bg-{{ category }} alert-icon-left alert-dismissible mb-2" role="alert">
                                              <span class="alert-icon">
                                                  <i class="fa fa-thumbs-o-up"></i>
                                              </span>
                                              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                  <span aria-hidden="true">&times;</span>
                                              </button>
                                              <strong class="text-gray-900">{{ message }}!</strong>
                                              
                                          </div>
                                      {%endif%}
                                      
                                      {% endfor %}
                                      {% endif %}
                                      {% endwith %}
              
                                <div class="row">

                                  {%if liste !=[]%} 
                                    <div class="col-md-12">
                                      <table class="table">
                                        <thead>
                                          <tr>
                                            <th>Titre</th>
                                            <th>Type de media</th>
                                            <th class="text-center">Statut </th>
                                            <th class="text-center">Action</th>
                                          </tr>
                                        </thead>
                                        <tbody>
                                          {%for media in liste%}
                                          <tr>
                                            <td> {{media.titre}} </td>
                                            <td> {{media.type_media}} </td>
                                            <td class="text-center">
                                              {%if media.statut==True%}
                                              <a href="{{url_for('media.statut', media_id=media.id)}}"><i class="fa fa-unlock" aria-hidden="true"></i></a>
                                              {%else%}
                                              <a href="{{url_for('media.statut', media_id=media.id)}}"><i class="fa fa-lock" aria-hidden="true"></i></a>
                                              {%endif%}
                                            </td>
                                            <td class="text-center"><a href="{{url_for('media.edit', media_id=media.id)}}"><i class="fa fa-edit" aria-hidden="true"></i></a></td>
                                          </tr>
                                          {%endfor%}
                                        </tbody>
                                      </table>
                                
                                    </div>
                                  {%else%}
                                    <div class="col-md-12">
                                      <p class="text-center" style="margin-top:100px">
                                          <i class="fa fa-folder success fa-5x text-center"></i>
                                          <h4 class="text-center">AUCUN MEDIA.</h4>
                                          <br><br><br><br><br><br>
                                      </p>
                                    </div>
                                  {%endif%}
                                </div> 
                
            </div><!--/card-block-->
          </div><!-- /form card login -->
          
        </div>
      </div>
    </div><!--/col-->
  </div><!--/row-->

{% endblock body %}

app/templates/media/index_audio.html
{% extends "layout/admini.html" %}
{% block css %}
<link href="{{ url_for('static', filename='plugins/mp3-audio.css')}}" rel="stylesheet">

{%endblock%}

{% block body %}
<div class="row">
  <div class="col-12 col-md-6 order-md-1 order-last">
    <h3>Média audio</h3>
    <br>
    <a href="{{url_for('media.ajouter')}} " class="d-none d-md-inline-block btn btn-md btn-info shadow-md">
    <i class="fa fa-music fa-md text-white-50"></i> Ajouter audio</a>
  </div>
  <div class="col-12 col-md-6 order-md-2 order-first">
      <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{url_for('main.dashboard')}}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{{url_for('media.index_audio')}}">Média audio</a></li>
          </ol>
      </nav>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
      <br>
      {% with messages= get_flashed_messages(with_categories=true) %}
                  {% if messages  %}
                      {% for category, message in messages %}
                          <div class="alert text-center alert-{{ category }}">
                              <b>{{ message }}</b>
                          </div>
                      {% endfor %}
                  {% endif %}
                  {% endwith %}
  </div>
</div>

<div class="row">
  <div class="col-md-12">
      <div class="row">
        {%if listes !=[]%} 
        {%for audio in listes%}
        
        <div class="col-md-3">
          <div class="card">
            <div class="card-block" style="margin: 2px;">
              <h4 class="card-title text-left">Titre: {{audio.titre}}</h4>
              <div class="mp3-audio">
                <audio controls class="mp3-auido">
                  <source src="{{audio.url_media}}" type="audio/mpeg">
                  Your browser does not support the audio element.
               </audio>
               <span class="justify-content-center">
                 <a href="{{url_for('media.sup_audio',media_id=audio.id)}}" onclick="return confirm('Voulez-vous vraiment suprimer cette audio?')"><i class="fa fa-close"></i> </a>
                {%if audio.statut==True%}
                  <a href="{{url_for('media.statut_audio',media_id=audio.id)}}"><i class="fa fa-unlock"></i> </a>
                {%else%}
                <a href="{{url_for('media.statut_audio',media_id=audio.id)}}"><i class="fa fa-lock"></i> </a>
                {%endif%}
                <a href="{{url_for('media.edit_audio',media_id=audio.id)}}"><i class="fa fa-edit"></i> </a>
                </span>
              </div>
            </div>
          </div>
        </div>

      </div>
        {%endfor%}
      
        {%else%}
          <div class="col-md-12">
            <p class="text-center" style="margin-top:100px">
                <i class="fa fa-music success fa-5x text-center"></i>
                <h4 class="text-center">AUCUNE AUDIO .</h4>
                <br><br><br><br><br><br>
            </p>
          </div>
        {%endif%}
  </div>
</div>

</div>


{% endblock body %}

{%block jsblock%}
{% endblock %}

app/templates/media/index_video.html
{% extends "layout/admini.html" %}
{% block css %}
<style>
  .cont {
  position: relative;
  width: 100%;
  overflow: hidden;
  padding-top: 66.66%; /* 3:2 Aspect Ratio */
}
  .responsive-iframe {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  width: 100%;
  height: 100%;
  border: none;
}
</style>
{%endblock%}

{% block body %}
<div class="row">
  <div class="col-12 col-md-6 order-md-1 order-last">
    <h3>Média Vidéo</h3>
    <br>
    <a href="{{url_for('media.ajouter')}} " class="d-none d-md-inline-block btn btn-md btn-primary shadow-md">
    <i class="fa fa-file-movie-o fa-md text-white-50"></i> Ajouter vidéo</a>
  </div>
  <div class="col-12 col-md-6 order-md-2 order-first">
      <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{url_for('main.dashboard')}}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{{url_for('media.index_video')}}">Média vidéo</a></li>
          </ol>
      </nav>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
      <br>
      {% with messages= get_flashed_messages(with_categories=true) %}
                  {% if messages  %}
                      {% for category, message in messages %}
                          <div class="alert text-center alert-{{ category }}">
                              <b>{{ message }}</b>
                          </div>
                      {% endfor %}
                  {% endif %}
                  {% endwith %}
  </div>
</div>

  <div class="row">
  <div class="col-md-12">
    
      <div class="row">
        {%if listes !=[]%} 
        {%for video in listes%}
        <div class="col-md-4">
          <!-- 16:9 -->
          <h4>{{video.titre}}</h4>
          <div class="cont">
            <embed  class=" responsive-iframe" src="{{video.url_media}}" style="margin-right:5px;"></embed> 
          </div>
          <span class="justify-content-center">
            <a href="{{url_for('media.sup_video',media_id=video.id)}}" onclick="return confirm('Voulez-vous vraiment suprimer cette vidéo?')"><i class="fa fa-close"></i> </a>
           {%if video.statut==True%}
             <a href="{{url_for('media.statut_video',media_id=video.id)}}"><i class="fa fa-unlock"></i> </a>
           {%else%}
           <a href="{{url_for('media.statut_video',media_id=video.id)}}"><i class="fa fa-lock"></i> </a>
           {%endif%}

           {%if video.alaune==True%}
             <a href="{{url_for('media.alune',med_id=video.id)}}"><i class="fa fa-certificate"></i> </a>
           {%else%}
           <a href="{{url_for('media.alune',med_id=video.id)}}"><i class="fa fa-circle"></i> </a>
           {%endif%}

           <a href="{{url_for('media.edit_video',media_id=video.id)}}"><i class="fa fa-edit"></i> </a>
           </span>
        </div>

        {%endfor%}

        {%else%}
          <div class="col-md-12">
            <p class="text-center" style="margin-top:100px">
                <i class="fa fa-file-movie-o success fa-5x text-center"></i>
                <h4 class="text-center">AUCUNE VIDEO .</h4>
                <br><br><br><br><br><br>
            </p>
          </div>
        {%endif%}
  </div>
  </div>

</div>


{% endblock body %}

{%block jsblock%}

{% endblock %}